from django.urls import path
from .views import (
    ClinicListView,
    ClinicSearchView,
    HospitalListByClinicView,
    HospitalSearchView,
    HospitalFilterListView,
    HospitalDetailView,
    DoctorListView,
    DoctorDetailView,
    DoctorSearchView,
    CityListView,
    AppointmentCreateView,
    PatientListView,
    PatientCreateView,
    PatientDetailView,
    ApointmentTypesListView,
    BloodListView,
    GenderListView,
    ApointmentListView,
    ApointmentDetailView
)
urlpatterns = [
    path('clinic/list', ClinicListView.as_view(), name='clinic_list'),
    path('clinic/search/<str:keyword>', ClinicSearchView.as_view(), name='clinic_search'),
    path('hospital/list/<int:clinic_id>', HospitalListByClinicView.as_view(), name='hospital_list_by_clinic'),
    path('hospital/search/<str:keyword>', HospitalSearchView.as_view(), name='hospital_search'),
    path('hospital/city/list', CityListView.as_view(), name='hospital_city_list'),
    path('hospital/filter-list', HospitalFilterListView.as_view(), name='hospital_list_by_filter'),
    path('hospital/detail/<int:hospital_id>', HospitalDetailView.as_view(), name='hospital_detail'),
    path('doctor/list/<int:hospital_id>', DoctorListView.as_view(), name='doctor_list_by_hospital'),
    path('doctor/detail/<int:doctor_id>', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/search/<str:keyword>', DoctorSearchView.as_view(), name='doctor_search'),
    path('appointment/create', AppointmentCreateView.as_view(), name='apointment_create'),
    path('appointment/type/list/<int:doctor_id>', ApointmentTypesListView.as_view(), name='apointment_type_list'),
    path('appointment/list', ApointmentListView.as_view(), name='apointment_list'),
    path('appointment/detail/<int:id>', ApointmentDetailView.as_view(), name='apointment_detail'),
    path('patient/list', PatientListView.as_view(), name='patient_list'),
    path('patient/blood/list', BloodListView.as_view(), name='blood_list'),
    path('patient/gender/list', GenderListView.as_view(), name='gender_list'),
    path('patient/create', PatientCreateView.as_view(), name='patient_create'),
    path('patient/detail/<int:patient_id>', PatientDetailView.as_view(), name='patient_detail'),
]
